version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
      - /var/run/docker.sock:/var/run/docker.sock # ?-
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
    postgres_data: