version: "3.9"
services:

  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/code/backend
    command: >
      bash -c "cd backend
      && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ./.env
    ports:
      - 8000:8000
    # depends_on:
    #   - db


      
  db:
    image: postgres:13.3
    env_file:
      - ./.env
    # volumes:
      # - ./init_data:/docker-entrypoint-initdb.d
      # - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"